'use strict';

// Canonical Batch Sender catalog mirrored from GM Market Bot's asset registry.
const TOKEN_CATALOG = Object.freeze([
  { name: 'Arco', mint: 'ARCoQ9dndpg6wE2rRexzfwgJR3NoWWhpcww3xQcQLukg', group: 'raw' },
  { name: 'Biomass', mint: 'MASS9GqtJz6ABisAxcUn3FeR4phMqH1XfG6LPKJePog', group: 'raw' },
  { name: 'Carbon', mint: 'CARBWKWvxEuMcq3MqCxYfi7UoFVpL9c4rsQS99tw6i4X', group: 'raw' },
  { name: 'Copper Ore', mint: 'CUore1tNkiubxSwDEtLc3Ybs1xfWLs8uGjyydUYZ25xc', group: 'raw' },
  { name: 'Diamond', mint: 'DMNDKqygEN3WXKVrAD4ofkYBc4CKNRhFUbXP4VK7a944', group: 'raw' },
  { name: 'Hydrogen', mint: 'HYDR4EPHJcDPcaLYUcNCtrXUdt1PnaN4MvE655pevBYp', group: 'raw' },
  { name: 'Iron Ore', mint: 'FeorejFjRRAfusN9Fg3WjEZ1dRCf74o6xwT5vDt3R34J', group: 'raw' },
  { name: 'Lumanite', mint: 'LUMACqD5LaKjs1AeuJYToybasTXoYQ7YkxJEc4jowNj', group: 'raw' },
  { name: 'Nitrogen', mint: 'Nitro6idW5JCb2ysUPGUAvVqv3HmUR7NVH7NdybGJ4L', group: 'raw' },
  { name: 'Rochinol', mint: 'RCH1Zhg4zcSSQK8rw2s6rDMVsgBEWa4kiv1oLFndrN5', group: 'raw' },
  { name: 'Silica', mint: 'SiLiCA4xKGkyymB5XteUVmUeLqE4JGQTyWBpKFESLgh', group: 'raw' },
  { name: 'Titanium Ore', mint: 'tiorehR1rLfeATZ96YoByUkvNFsBfUUSQWgSH2mizXL', group: 'raw' },
  { name: 'Ammo', mint: 'ammoK8AkX2wnebQb35cDAZtTkvsXQbi82cGeTnUvvfK', group: 'components' },
  { name: 'Copper', mint: 'CPPRam7wKuBkYzN5zCffgNU17RKaeMEns4ZD83BqBVNR', group: 'components' },
  { name: 'Copper Wire', mint: 'cwirGHLB2heKjCeTy4Mbp4M443fU4V7vy2JouvYbZna', group: 'components' },
  { name: 'Crystal Lattice', mint: 'CRYSNnUd7cZvVfrEVtVNKmXiCPYdZ1S5pM5qG2FDVZHF', group: 'components' },
  { name: 'Electromagnet', mint: 'EMAGoQSP89CJV5focVjrpEuE4CeqJ4k1DouQW7gUu7yX', group: 'components' },
  { name: 'Electronics', mint: 'ELECrjC8m9GxCqcm4XCNpFvkS8fHStAvymS6MJbe3XLZ', group: 'components' },
  { name: 'Energy Substrate', mint: 'SUBSVX9LYiPrzHeg2bZrqFSDSKkrQkiCesr6SjtdHaX', group: 'components' },
  { name: 'Field Stabilizers', mint: 'FiELD9fGaCgiNMfzQKKZD78wxwnBHTwjiiJfsieb6VGb', group: 'components' },
  { name: 'Food', mint: 'foodQJAztMzX1DKpLaiounNe2BDMds5RNuPC6jsNrDG', group: 'components' },
  { name: 'Framework', mint: 'FMWKb7YJA5upZHbu5FjVRRoxdDw2FYFAu284VqUGF9C2', group: 'components' },
  { name: 'Fuel', mint: 'fueL3hBZjLLLJHiFH9cqZoozTG3XQZ53diwFPwbzNim', group: 'components' },
  { name: 'Graphene', mint: 'GRAPHKGoKtXtdPBx17h6fWopdT5tLjfAP8cDJ1SvvDn4', group: 'components' },
  { name: 'Hydrocarbon', mint: 'HYCBuSWCJ5ZEyANexU94y1BaBPtAX2kzBgGD2vES2t6M', group: 'components' },
  { name: 'Iron', mint: 'ironxrUhTEaBiR9Pgp6hy4qWx6V2FirDoXhsFP25GFP', group: 'components' },
  { name: 'Magnet', mint: 'MAGNMDeDJLvGAnriBvzWruZHfXNwWHhxnoNF75AQYM5', group: 'components' },
  { name: 'Particle Accelerator', mint: 'PTCLSWbwZ3mqZqHAporphY2ofio8acsastaHfoP87Dc', group: 'components' },
  { name: 'Polymer', mint: 'PoLYs2hbRt5iDibrkPT9e6xWuhSS45yZji5ChgJBvcB', group: 'components' },
  { name: 'Power Source', mint: 'PoWRYJnw3YDSyXgNtN3mQ3TKUMoUSsLAbvE8Ejade3u', group: 'components' },
  { name: 'Radiation Absorber', mint: 'RABSXX6RcqJ1L5qsGY64j91pmbQVbsYRQuw1mmxhxFe', group: 'components' },
  { name: 'Strange Emitter', mint: 'EMiTWSLgjDVkBbLFaMcGU6QqFWzX9JX6kqs1UtUjsmJA', group: 'components' },
  { name: 'Steel', mint: 'STEELXLJ8nfJy3P4aNuGxyNRbWPohqHSwxY75NsJRGG', group: 'components' },
  { name: 'Super Conductor', mint: 'CoNDDRCNxXAMGscCdejioDzb6XKxSzonbWb36wzSgp5T', group: 'components' },
  { name: 'Survey Data Unit', mint: 'SDUsgfSZaDhhZ76U3ZgvtFiXsfnHbf2VrzYxjBZ5YbM', group: 'components' },
  { name: 'Titanium', mint: 'TTNM1SMkM7VKtyPW6CNBZ4cg3An3zzQ8NVLS2HpMaWL', group: 'components' },
  { name: 'Toolkits', mint: 'tooLsNYLiVqzg8o4m3L2Uetbn62mvMWRqkog6PQeYKL', group: 'components' },
  { name: 'Busan Pulse', mint: 'puLSevjndZbxLSynPQgGVh7oPCGimhqLppV5Kb8o3S8', group: 'ships' },
  { name: 'Fimbul Airbike', mint: 'Fw8PqtznYtg4swMk7Yjj89Tsj23u5CJLfW5Bk8ro4G1s', group: 'ships' },
  { name: 'Fimbul ECOS Unibomba', mint: '9zrgra3XQkZPt8XNs4fowbqmj7B8bBx76aEmsKSnm9BW', group: 'ships' },
  { name: 'Ogrika Ruch', mint: 'RUCHH4AcvodBcndmcT17KUBbd5ee5LQtmpsfvBVNnPH', group: 'ships' },
  { name: 'Opal Jet', mint: 'Ev3xUhc1Leqi4qR2E5VoG9pcxCvHHmnAaSRVPg485xAT', group: 'ships' },
  { name: 'Pearce X4', mint: '2iMhgB4pbdKvwJHVyitpvX5z1NBNypFonUgaSAt9dtDt', group: 'ships' },
  { name: 'VZUS solos', mint: 'HjFijcGWKgfDwGpFX2rqFwEU9jtEgFuRQAJe1ERXFsA3', group: 'ships' },
  { name: 'Calico Maxhog', mint: 'GxpbUDxYYvxiUejHcAMzeV2rzdHf6KZZvT86ACrpFgXa', group: 'ships' },
  { name: 'Calico Scud', mint: 'F3HitKsp52UPqBMEWSeTFqrGgnfYbS9DMrJCz9dM3w6D', group: 'ships' },
  { name: 'Fimbul Lowbie', mint: '7Xs3yt9eJPuEexZrKSGVbQMXHwWUKHGeDZnM4ZksZmyS', group: 'ships' },
  { name: 'Ogrika Niruch', mint: '7SUoWHWWJCxCe5g9XqZkCRufGHXRV8nauuz69HPjuewr', group: 'ships' },
  { name: 'Opal Jetjet', mint: '9ABNesWj7NVdkDgko7UjVaDp5pTh8a6wfXHLWz3bZM6W', group: 'ships' },
  { name: 'Pearce X5', mint: '267DbhCypYzvTqv72ZG5UKHeFu56qXFsuoz3rw832eC5', group: 'ships' },
  { name: 'Armstrong IMP Tip', mint: 'DTbNmLWfu1pm4AuXRKYTApnDNfxMz73VET7nW5wizG5t', group: 'ships' },
  { name: 'Busan Thrill of Life', mint: 'FTk1E5UoWkiZEUttCWSYYaVokxWNNp3yJ42HbNDCAkdt', group: 'ships' },
  { name: 'Calico Medtech', mint: '4gR3ChfdQxR4BTbgeWSdf6b8kD8Ysu6WBAQqtJ9oLgbF', group: 'ships' },
  { name: 'Calico Shipit', mint: 'SHiPitEZcCoyXEKqw9ovCdYeNzck9uVbb1KCcsHaGhc', group: 'ships' },
  { name: 'Fimbul BYOS Earp', mint: '6SqLuwHNRC1qjo9KATLKJLszFHMWyYaNxDXraCEUtfdR', group: 'ships' },
  { name: 'Ogrika Mik', mint: 'FMHHwUB6amLWYhWxtiZHC2g5azy9usPTLMq46N3HEgFU', group: 'ships' },
  { name: 'Opal Rayfam', mint: 'RaYfM1RLfxQJWF8RZravTshKj1aHaWBNXF94VWToY9n', group: 'ships' },
  { name: 'Pearce R6', mint: 'Fys8J53cquYsg5zYfeZStVGNwM9FopFw8QFkiE9CCR1J', group: 'ships' },
  { name: 'Pearce X6', mint: '8RveLFEyteyL1vbCKPQJxjf3JT1ACyrzs46TXbJStrHG', group: 'ships' },
  { name: 'Rainbow Chi', mint: 'DsJHgpnNovjJ981QJJnqMggexAekNawbSavfV1QuTpis', group: 'ships' },
  { name: 'Tufa Feist', mint: 'HsdbLvZrEgN2ZhsrZs5ag4F2FNFCHjjuXPfbVAhkeJBZ', group: 'ships' },
  { name: 'VZUS ambwe', mint: 'H2jHqvXA2oxSpEp6dKkpK7WeszQEdFW5n25mNfrJFAc1', group: 'ships' },
  { name: 'Armstrong IMP Tap', mint: 'ARNZXUQoBKx3JCX3UJB4aitSnvcjMMphN9YVDFy1PdKq', group: 'ships' },
  { name: 'Calico ATS Enforcer', mint: '2XYd22LSFGxN7kWgoEeaXVZqgrsPeQLHLEgNhnS12Mny', group: 'ships' },
  { name: 'Calico Compakt Hero', mint: 'AkNbg12E9PatjkiAWJ3tAbM479gtcoA1gi6Joa925WKi', group: 'ships' },
  { name: 'Calico Evac', mint: '4txpjHspP4usEsQTr3AcrpyHVjN4fi3d4taM6cmKJnd1', group: 'ships' },
  { name: 'Fimbul Mamba', mint: '6Zj61HuX1E7SCUCf9WsKXw1jdJCobAwK4RSjZvbv35tM', group: 'ships' },
  { name: 'Fimbul Mamba EX', mint: 'MEXfyQHowwqoTHsN6yjfeXVaxZxALUFJAHuzY8gFiUu', group: 'ships' },
  { name: 'Fimbul BYOS Packlite', mint: '7V9C2XUQgCb31n7hGKqKGu4ENcvqXhJLJzU77CAQtXhw', group: 'ships' },
  { name: 'Fimbul BYOS Ranger', mint: 'RNGRjeGyFeyFT4k5aTJXKZukVx3GbG215fcSQJxg64G', group: 'ships' },
  { name: 'Ogrika Tursic', mint: 'J8Q6jYsrhhaeczyPBo9xzVyy4GpfCnJwj14LJn2HnuKp', group: 'ships' },
  { name: 'Pearce F4', mint: '9MvZS3TVfv4DZL9W2pT12po384aBHf7wi89KXQ9Z7uwW', group: 'ships' },
  { name: 'Rainbow Om', mint: 'HzBx8PP86pyPrrboTHqPYWhxnEB5vXDHDBP8femWfPTS', group: 'ships' },
  { name: 'VZUS opod', mint: '9czEqEZ4EkRt7N3HWDcw9qqwys3xRRjGdbn8Jhk8Khwj', group: 'ships' },
  { name: 'Fimbul BYOS Butch', mint: 'BBUTCn3jcXKjFYuuYtY8MNo8bDg9VsZaKwaSYnRr2Qse', group: 'ships' },
  { name: 'Fimbul ECOS Greenader', mint: 'FpwV1Da6BZJnYPr1JSLUm14UwBmZHA7J5WLY4TXgbde8', group: 'ships' },
  { name: 'Ogrika Sunpaa', mint: '4b4mhSySBcryzBPamw8v4xeneFRA6xTUA4JA99w6vqey', group: 'ships' },
  { name: 'Ogrika Thripid', mint: 'CWxNX9sTexuqvQefqskhP9f6AP5C8hq2VNkicRseqAT5', group: 'ships' },
  { name: 'Opal Bitboat', mint: '8pPDsMNcz4m8jaajFMFXHGcvaeVeiQhcenvSD6a4XNyq', group: 'ships' },
  { name: 'Pearce R8', mint: '2bCgKTo11QayWBy6QryHZMqZL2ZgWd5LEAZKiTGQi4g7', group: 'ships' },
  { name: 'Rainbow Arc', mint: 'EbLBLN44BVLjifLNBbchXFr8QjEkAGYENKuNEaDuyVPL', group: 'ships' },
  { name: 'Armstrong IMP', mint: 'GmVKV9W3qZcERxk7hjqwRDcn9Kgtz3XDi7KfFLdGqyaW', group: 'ships' },
  { name: 'Busan Maiden Heart', mint: '6HzZJwrcuBBmrE7SLDfxheZGAD3NYJ531C9JsNesL9BP', group: 'ships' },
  { name: 'Calico Guardian', mint: 'DdpXnnYsyUQgJby8TDHbmPwkKyGF4U6bXwCXTQZsrfKP', group: 'ships' },
  { name: 'Fimbul Sledbarge', mint: 'SLEDkN916vvcpucY9Vn7tAzNXRcxsq71kkXzaj1cxoX', group: 'ships' },
  { name: 'Fimbul ECOS Bombarella', mint: '7M6RHgPiHXiZAin5ManH63cLYGt3miQ54KaGynUQoERS', group: 'ships' },
  { name: 'Ogrika Jod Asteris', mint: 'HJBmBYyGR8z1oajAM4jiK46uobuxeJoKDYpFwzWHBvhb', group: 'ships' },
  { name: 'Pearce C9', mint: '5f1jUARhtSypVA4uTpgpLp76WYGdB2dGr8zMbh4WjYRf', group: 'ships' },
  { name: 'Pearce D9', mint: 'H3cgBXWpUiNsYjUWS7cNR5Bmehh7k5CgpJccc5wSfRbJ', group: 'ships' },
  { name: 'VZUS ballad', mint: 'FFkPvwLDYuKDW9eAAr5UNfuX3U9PcTGeSk7gqNX7EpNc', group: 'ships' },
  { name: 'Fimbul BYOS Tankship', mint: '4ns3shP4WunCtJbr2HFu31RjjxSJxDymEFcBZxiHr11s', group: 'ships' },
  { name: 'Fimbul ECOS Treearrow', mint: 'HqPN13pLUVJRiuGSsKjfWZvGKAagK98PshuKu51bnG4E', group: 'ships' },
  { name: 'Pearce C11', mint: '9ifQ16N5DdUFoejCwsgR73ihUwadAe3srCo9HhQe2zL2', group: 'ships' },
  { name: 'Busan The Last Stand mk. VIII', mint: 'Cvy691GFw2j3H8e6yf7hZtaQi5P3skQR4gzM6UWvcL7L', group: 'ships' },
  { name: 'Fimbul ECOS Superphoenix', mint: '2BMTgfgapuqYBwSRGu6HCafwDGRVTxMkQVhYrNWQGTWH', group: 'ships' },
  { name: 'Pearce T1', mint: '56nh4FvMJnSpkWJcmXc1nJtYhSQXuqb7nVMGALr31RVc', group: 'ships' },
  { name: 'Rainbow Phi', mint: 'phi4PYgmxeTMLLpGkU87T16VUZ6AjWZESkfT1JGJ635', group: 'ships' },
  { name: 'Silver 1 Card Pack', mint: 'CPS1gTEio7PqnAmDmWuCfiTBbtDRRsA8cwdQe3TqgGsf', group: 'crew-packs' },
  { name: 'Silver 5 Card Pack', mint: 'CPS5deX4R2BkA1X4SRrk5V2LqmT7CXwNdnC5syrpAmDK', group: 'crew-packs' },
  { name: 'Gold 1 Card Pack', mint: 'CPG1B4jv6D2cZRkfXWawxSrE9SvhxdiDT1yKP4cNmHSe', group: 'crew-packs' },
  { name: 'Gold 5 Card Pack', mint: 'CPG5JB1Z83TsYYCaVJLLpWVcoBBAnQ2T2nzmR9tbi3WU', group: 'crew-packs' },
  { name: 'Presale 10 Card Pack', mint: 'CRWPXjZw73dMW3pG7UMhVWDrfk5NnzMCMuWj6hVLMCYm', group: 'crew-packs' },
  { name: 'Platinum 1 Card Pack', mint: 'CPP1iv66iqZYeGEYuGAmjTbRJMbNazCWu8r2Ln5TUsc5', group: 'crew-packs' },
  { name: 'Platinum 5 Card Pack', mint: 'CPP5rhCt7tvjco6vbVMawzg4WHmr3Thr67y7PcBcbfSz', group: 'crew-packs' },
  { name: 'Fimbul Airbike (ship parts)', mint: 'SP935x1ksMqw2kDi7Tg6E9Rt4sKFBx9CKM227vgYNTK', group: 'ship-parts' },
  { name: 'Fimbul ECOS Unibomba (ship parts)', mint: 'SPjm3Q229eBCftiidm8HEfwyuEWwPi7pByzSnmouKHn', group: 'ship-parts' },
  { name: 'Ogrika Ruch (ship parts)', mint: 'SP8wv47jZkfqyBXH184f8TqY7A9QXUswkRCD6k9hVg2', group: 'ship-parts' },
  { name: 'Opal Jet (ship parts)', mint: 'SPUAxnUwDeWzzBcXhB2JdTNgyDY2Quwxz6G2GQMmsQj', group: 'ship-parts' },
  { name: 'Pearce X4 (ship parts)', mint: 'SPX4TsjfMSyMGJqAASY9NhKzTSd8XmTuMu1eYWwFw3u', group: 'ship-parts' },
  { name: 'VZUS solos (ship parts)', mint: 'SPpEEM5tPipQc7GHTyBtXw1G2s7gfWu8UVqikwJgp6j', group: 'ship-parts' },
  { name: 'Calico Maxhog (ship parts)', mint: 'SPGRLJuSZwLcejjiBAqfh8YJVYYDa7DYA2QU99h9M14', group: 'ship-parts' },
  { name: 'Fimbul Lowbie (ship parts)', mint: 'SPoTBZxWKJ8ayxufK2mNKLmcbDABqSmNMVPQot5q9uV', group: 'ship-parts' },
  { name: 'Ogrika Niruch (ship parts)', mint: 'SPQuyr4AsPoRRLBpHcgRhatoaNqdS4eTCx8xHyW6dp5', group: 'ship-parts' },
  { name: 'Opal Jetjet (ship parts)', mint: 'SPjRydMf7VDceWDR6L9B8rHrrERbRA8h1pD3GzwFvwd', group: 'ship-parts' },
  { name: 'Pearce X5 (ship parts)', mint: 'SPdndwbTiwYvTqqmUcruVcSXPuVEEwzkTxYietBh7Gh', group: 'ship-parts' },
  { name: 'Armstrong IMP Tip (ship parts)', mint: 'SP9t6DXorrHvmWnQp2fWniuLzE9gi33Q6CceKiyu9s6', group: 'ship-parts' },
  { name: 'Busan Thrill of Life (ship parts)', mint: 'SPDDvSwj33te4d1NfVGmTyKsixzrV3A5b6riaQRriLo', group: 'ship-parts' },
  { name: 'Calico Medtech (ship parts)', mint: 'SPGkQWEj9DmaGH3HkS6nobCwUCYDspYMgTQcXfXMNX9', group: 'ship-parts' },
  { name: 'Calico Shipit (ship parts)', mint: 'SPeLpYEcQLLenUEGUhs6yuqUo7NjZkWjkRXLgYkGyjQ', group: 'ship-parts' },
  { name: 'Fimbul BYOS Earp (ship parts)', mint: 'SPejJQrb8HhKob3RkVGmT5gN9uSdeY8fXMX7jFqfWvc', group: 'ship-parts' },
  { name: 'Ogrika Mik (ship parts)', mint: 'SP9Z5zYNRLTikxMYdcLUhTHmaarXmz1kjYoVja2JDWP', group: 'ship-parts' },
  { name: 'Opal Rayfam (ship parts)', mint: 'SPPzuW7FaABwfnhKoBVb2HiaRAs8BqfBdSgU1G1W5LA', group: 'ship-parts' },
  { name: 'Pearce R6 (ship parts)', mint: 'SPNcYhJiw1uLP1Dc5TUm4FKewaNWLeTBgLG3i6oMW3M', group: 'ship-parts' },
  { name: 'Pearce X6 (ship parts)', mint: 'SPKi4Zirg1ekZKxsgXeYvpbHzMGjAUtg6McvKDep9WA', group: 'ship-parts' },
  { name: 'Rainbow Chi (ship parts)', mint: 'SPADReGEYZNVNeuDDAtPdz2f243nhB8LzUpUYt1nc8L', group: 'ship-parts' },
  { name: 'Tufa Feist (ship parts)', mint: 'SPQm3JuAfgEdnt7DYpM13mKy5woivy2oHZeTTTvDgWK', group: 'ship-parts' },
  { name: 'VZUS ambwe (ship parts)', mint: 'SPQLP2vM2BPwWPCVKYjV26Qq1VNYjF7hgqWUnSBz9YF', group: 'ship-parts' },
  { name: 'Armstrong IMP Tap (ship parts)', mint: 'SP4g7dXZBAMPGhjNi46bM2oqMkHx7j5PvsFqqpymZRb', group: 'ship-parts' },
  { name: 'Calico ATS Enforcer (ship parts)', mint: 'SPYX1UhN7Wo5bhF7cex34KrigYppE1GjMWqBUipsVMz', group: 'ship-parts' },
  { name: 'Calico Compakt Hero (ship parts)', mint: 'SPZVqpuczgvFRokSaSvxNro2bQMBvbMqgrffbochuSn', group: 'ship-parts' },
  { name: 'Calico Evac (ship parts)', mint: 'SPLxmJj7AwFA96d2coWx1rs1q8tcoD8qBJbcy1RfjAj', group: 'ship-parts' },
  { name: 'Fimbul Mamba (ship parts)', mint: 'SPi7AZjSBSCu3enPGBTE8krSqUrbcjXQfqKrbdPSxH8', group: 'ship-parts' },
  { name: 'Fimbul Mamba EX (ship parts)', mint: 'SPfWuneqCNZMpygohFFY2czsC2dNf5KG85DwzAW2JKt', group: 'ship-parts' },
  { name: 'Fimbul BYOS Packlite (ship parts)', mint: 'SPjkody6rBMwLEKjPrpT7B8Q5WnbrQyCJzwf9ya3sYJ', group: 'ship-parts' },
  { name: 'Fimbul BYOS Ranger (ship parts)', mint: 'SPnu72dCxh45NbFXZv6PJu2o4qzCV3192dt75vni3Vj', group: 'ship-parts' },
  { name: 'Ogrika Tursic (ship parts)', mint: 'SPHMQcpDQxAwERjHeGcwbcg7CwTZSXNCQbS2PahPHVE', group: 'ship-parts' },
  { name: 'Pearce F4 (ship parts)', mint: 'SPzNT8sx2s36Xbh4Cyfpc64Fg6HddNJJbv1J8bPnYMG', group: 'ship-parts' },
  { name: 'Rainbow Om (ship parts)', mint: 'SPrRobRPWhJWjVEsbL5r8B3fRbvee9sLhGG678bv2uf', group: 'ship-parts' },
  { name: 'VZUS opod (ship parts)', mint: 'SPvvHMuffWKRz9dFAGkXaf9MeBTPEskpN1PvC53oFwz', group: 'ship-parts' },
  { name: 'Fimbul BYOS Butch (ship parts)', mint: 'SPZzXCbAo74ZBzmrVUgaMr8HN9pSGSbu62GcfTks3tY', group: 'ship-parts' },
  { name: 'Fimbul ECOS Greenader (ship parts)', mint: 'SP7YWWAZDe8drm2VU8HFVvTVJzrDzvK8C2ee2SE8JXn', group: 'ship-parts' },
  { name: 'Ogrika Sunpaa (ship parts)', mint: 'SPoTGuqXiCgbPFpvTn22erQMuTHFYYsbnxEfhhJqYga', group: 'ship-parts' },
  { name: 'Ogrika Thripid (ship parts)', mint: 'SP2eWeShQ2KrGWrxtZbDAAXCdfof43FJueUo1KqAxzq', group: 'ship-parts' },
  { name: 'Opal Bitboat (ship parts)', mint: 'SPXgrxorCaXHvdfhQbwkDpetUXCZAsDs3E4MZDUdcTp', group: 'ship-parts' },
  { name: 'Pearce R8 (ship parts)', mint: 'SP1fvRw24ToEsmjsZN7c8sMAusSA48C17hcn9qrGVAR', group: 'ship-parts' },
  { name: 'Rainbow Arc (ship parts)', mint: 'SP6PnRjWPHz3RxF15qy9PXXLkkirsyibb2V6S3P8u5o', group: 'ship-parts' },
  { name: 'Armstrong IMP (ship parts)', mint: 'SPx7SaZbdvZ2DAq5nk1QAMUAZaqmETT6vyMmBpEotsB', group: 'ship-parts' },
  { name: 'Busan Maiden Heart (ship parts)', mint: 'SP4CAzVMkiYHQvMNUj6JJ9GL3tK1RU3HxY3iR6oPvGE', group: 'ship-parts' },
  { name: 'Calico Guardian (ship parts)', mint: 'SPaBk8C9A1ubKBVSBJvdUQWMd9fQmYdSd7kTf5XH2pv', group: 'ship-parts' },
  { name: 'Fimbul Sledbarge (ship parts)', mint: 'SPBLA6iXiTJ8LbmYTxPpzqKcgvrYaaRjAtCtppYkop4', group: 'ship-parts' },
  { name: 'Fimbul ECOS Bombarella (ship parts)', mint: 'SPAuBnNyFuJZJZkveJEpizp4o56KEvPmnCx9HMAkXrR', group: 'ship-parts' },
  { name: 'Ogrika Jod Asteris (ship parts)', mint: 'SP1MdhiYHXosr2geEse9tK8rGBnkf7nsdMjFHXgnQnQ', group: 'ship-parts' },
  { name: 'Pearce C9 (ship parts)', mint: 'SPTDyxPxs3NwaArzZp5xrtLSujtpn6nTbLsgsRProrD', group: 'ship-parts' },
  { name: 'Pearce D9 (ship parts)', mint: 'SPjrTK2QaAxz3EMMzm1K1Q5jdGvkBR4Nu7QtiBNCB7c', group: 'ship-parts' },
  { name: 'VZUS ballad (ship parts)', mint: 'SPQ6rRhhy9CBb9FyhPsydF7MBvMGX2Ekg55zBwagSUc', group: 'ship-parts' },
  { name: 'Fimbul BYOS Tankship (ship parts)', mint: 'SPUynJ6UU4LRKWMogCqMC1SFxzqhh3mNLmqwtDxU2Sw', group: 'ship-parts' },
  { name: 'Fimbul ECOS Treearrow (ship parts)', mint: 'SP9odyU6RPeW6WRY9e5g7K6qHR7KvnsBtnuzab5eX9G', group: 'ship-parts' },
  { name: 'Pearce C11 (ship parts)', mint: 'SP16CbhAfUvbeWjQveE6j22k2okBGAbEKmxEcSUgLFi', group: 'ship-parts' },
  { name: 'Busan The Last Stand mk. VIII (ship parts)', mint: 'SPaAfAJk3RWu5x81VT2Spf4FGwXsLvNBeirMKXYhWVT', group: 'ship-parts' },
  { name: 'Fimbul ECOS Superphoenix (ship parts)', mint: 'SPrYTd7sBCmPhNNfyoMMPZxthxHiDtTo1ffbijobouf', group: 'ship-parts' },
  { name: 'Pearce T1 (ship parts)', mint: 'SPLwp5EsvGcH4uM2SbvMDTTXbe92LFVWrHwoUTXoxdP', group: 'ship-parts' },
  { name: 'Rainbow Phi (ship parts)', mint: 'SPBYj9Ef1q7c4inWJfCUDJJr2KLUgZ4PtB7g46zBYU1', group: 'ship-parts' },
].map(Object.freeze));

const TOKEN_BY_MINT = new Map(TOKEN_CATALOG.map((token) => [token.mint, token]));

module.exports = { TOKEN_BY_MINT, TOKEN_CATALOG };
